

// Types para los pokemones

export const OBTENER_POKEMONS = "OBTENER_POKEMONS";
export const OBTENER_POKEMONS_SUCCESS = "OBTENER_POKEMONS_SUCCESS";
export const OBTENER_POKEMONS_ERROR = "OBTENER_POKEMONS_ERROR";
export const OBTENER_POKEMON = "OBTENER_POKEMON";
export const OBTENER_POKEMON_SUCCESS = "OBTENER_POKEMON_SUCCESS";
export const OBTENER_POKEMON_ERROR = "OBTENER_POKEMON_ERROR";