

// Types para los pokemones

export const OBTENER_POKEMONS = "OBTENER_POKEMONS";
export const OBTENER_POKEMONS_SUCCESS = "OBTENER_POKEMONS_SUCCESS";
export const OBTENER_POKEMONS_ERROR = "OBTENER_POKEMONS_ERROR";
export const OBTENER_POKEMON = "OBTENER_POKEMON";
export const OBTENER_POKEMON_SUCCESS = "OBTENER_POKEMON_SUCCESS";
export const OBTENER_POKEMON_ERROR = "OBTENER_POKEMON_ERROR";
export const OBTENER_POKEMON_SEARCH_SUCCESS = "OBTENER_POKEMONS_SEARCH_SUCCESS";
export const OBTENER_POKEMON_SEARCH_ERROR = "OBTENER_POKEMONS_SEARCH_ERROR";

export const OBTENER_POKEMONS_GLOBAL = "OBTENER_POKEMONS_GLOBAL"
export const OBTENER_POKEMONS_GLOBAL_SUCCESS = "OBTENER_POKEMONS_GLOBAL_SUCCESS";
export const OBTENER_POKEMONS_GLOBAL_ERROR = "OBTENER_POKEMONS_GLOBAL_ERROR";

export const OBTENER_TERMINO_SUCCESS = "OBTENER_TERMINO_SUCCESS";
export const OBTENER_TERMINO_ERROR = "OBTENER_TERMINO_ERROR"

export const CAMBIAR_OFFSET = "CAMBIAR_OFFSET";